eligibility/urls.py
from django.urls import include, path

from eligibility import views
from eligibility.views import nations, players

player_urls = [
    path("create", players.player_create, name="player"),
    path("<uuid:pk>", players.player_edit, name="player"),
    path("<uuid:pk>/exception", players.player_exception_request, name="exception"),
    path("<uuid:player>/declarations/create", players.declaration_create, name="declaration"),
    path("<uuid:player>/declarations/<uuid:pk>", players.PlayerDeclarationView.as_view(), name="declaration"),
    path("<uuid:player>/parents/create", players.parent_edit, name="parent"),
    path("<uuid:player>/parents/<uuid:pk>", players.parent_edit, name="parent"),
    path("<uuid:player>/parents/<uuid:parent>/grandparent/create", players.grandparent_edit, name="grandparent"),
    path("<uuid:player>/parents/<uuid:parent>/grandparent/<uuid:pk>", players.grandparent_edit, name="grandparent"),
]

nation_urls = [
    path("<uuid:uuid>", nations.declaration_verify, name="declaration"),
    path("events", nations.event_list, name="events"),
    path("events/<uuid:event>/squad", nations.event_notify_squad, name="squad"),
    path("events/<uuid:event>/team", nations.event_notify_team, name="team"),
]

urlpatterns = [
    path("", views.index, name="index"),
    path("players", players.player_list, name="players"),
    path("players/", include(player_urls)),
    path("nations", nations.declaration_list, name="nations"),
    path("nations/", include(nation_urls)),
]

fit_tournaments/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("eligibility.urls")),
    path("", include("social_django.urls", namespace="social")),
    path("", include("accreditation.urls")),
    path("impersonate/", include("impersonate.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("userprofile.urls")),
    path("sentry-debug", trigger_error),
    path("__debug__/", include("debug_toolbar.urls")),
]

eligibility/models.py
import uuid
from typing import List

from dirtyfields import DirtyFieldsMixin
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.functional import cached_property

from eligibility.fields import BooleanField, JSONField
from eligibility.managers import PersonManager, PlayerDeclarationManager, PlayerManager
from eligibility.utils import person_clean, person_declaration_clean


class Country(models.Model):
    iso3166a3 = models.CharField(max_length=3, primary_key=True)
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "countries"
        ordering = ("name",)

    def __str__(self):
        return self.name


class Person(DirtyFieldsMixin, models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    name = models.CharField(max_length=100)
    date_of_birth = models.DateField(help_text="Please use YYYY-MM-DD format.")
    country_of_birth = models.ForeignKey(
        Country,
        blank=True,
        null=True,
        help_text="If not one of these countries, leave blank and type below.",
        on_delete=models.PROTECT,
        related_name="%(class)ss_born",
    )
    country_of_birth_other = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        default=None,
        help_text="Only valid if not one of the countries listed above.",
    )

    # Allow exceptions to the minimums
    exceptions = models.TextField(blank=True, null=True)
    min_biological_parents = models.PositiveSmallIntegerField(blank=True, null=True)

    class Meta:
        abstract = True
        ordering = ("name",)

    def __str__(self):
        return self.name

    def clean(self):
        country_names = {
            c.lower() for c in Country.objects.values_list("name", flat=True)
        }
        person_clean(self, country_names)

    def eligible(self) -> List[str]:
        """
        Query across Parent and GrandParent relations for all eligibilities.
        """
        countries = {self.birthplace, self.residency}
        for country in self.parents_birthplace + self.grandparents_birthplace:
            if country:
                countries.add(country)
        return sorted(countries)


class Player(Person):
    residence = models.ForeignKey(
        Country,
        blank=True,
        null=True,
        help_text="If not one of these countries, leave blank and type below.",
        on_delete=models.PROTECT,
        related_name="players_resident",
    )
    residence_other = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        default=None,
        help_text="Only valid if not one of the countries listed above.",
    )

    objects = PlayerManager()

    def get_absolute_url(self):
        return reverse("player", kwargs={"pk": self.pk})

    def can_declare(self):
        min_biological_parents = self.min_biological_parents or 2
        if self.biological_parent_count < min_biological_parents:
            raise ValueError(
                f"Must have at least {min_biological_parents} biological parents."
            )
        for parent in self.parent_set.all():
            biological_parents = 0
            min_biological_parents = parent.min_biological_parents or 2
            for grandparent in parent.grandparent_set.all():
                if not grandparent.adopted:
                    biological_parents += 1
            if biological_parents < min_biological_parents:
                raise ValueError(
                    f"At least one parent does not have at least "
                    f"{min_biological_parents} biological parents."
                )

    @cached_property
    def can_declare_bool(self):
        try:
            self.can_declare()
        except ValueError:
            return False
        return True

    def unable_to_declare_reason(self):
        try:
            self.can_declare()
        except ValueError as exc:
            return str(exc)


class Parent(Person):
    child = models.ForeignKey(Player, on_delete=models.PROTECT)
    adopted = BooleanField(
        default=False,
        help_text="Tick if this parental relationship is not biological.",
    )

    objects = PersonManager()

    class Meta:
        unique_together = ("child", "name")


class GrandParent(Person):
    child = models.ForeignKey(Parent, on_delete=models.PROTECT)
    adopted = BooleanField(
        default=False,
        help_text="Tick if this parental relationship is not biological.",
    )

    objects = PersonManager()

    class Meta:
        verbose_name = "grandparent"
        unique_together = ("child", "name")


class PlayerDeclaration(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    player = models.ForeignKey(
        Player, related_name="declarations", on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        get_user_model(),
        editable=False,
        related_name="declarations",
        on_delete=models.PROTECT,
        help_text="The user who made this declaration for the player.",
    )
    timestamp = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        help_text="Automatically recorded time that the declaration was saved.",
    )
    name = models.CharField(
        # Despite having a fkey back to the Player, we want to trap the content that
        # was current at the time they made the declaration, so this redundancy is
        # acceptable.
        editable=False,
        max_length=100,
        help_text="Name of the player that made this declaration.",
    )
    eligible_for = models.JSONField(
        # We could extract this from the "data" field (below) however that would
        # require the logic to be baked in too (as this policy changes over time, we
        # don't need to special case evaluation based on timestamp).
        editable=False,
        help_text=(
            "List of countries that submitted data indicates the player is eligible "
            "to represent."
        ),
    )
    elected_country = models.ForeignKey(
        Country,
        related_name="available_for_selection",
        help_text=(
            "Country that this player has elected to play for, from their available "
            "choices."
        ),
        on_delete=models.PROTECT,
    )
    data = JSONField(
        editable=False,
        help_text="Serialized data that locks the values in time.",
    )
    evidence_nation = JSONField(
        null=True,
        editable=False,
        help_text="Record of documents sighted by FIT member.",
    )
    supersceded_by = models.ForeignKey(
        "self",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    verified_by = models.ForeignKey(
        get_user_model(),
        blank=True,
        null=True,
        on_delete=models.PROTECT,
    )
    verified_comments = models.TextField(
        blank=True,
        null=True,
        help_text="Brief details of what was sighted during the verification process.",
    )

    objects = PlayerDeclarationManager()

    class Meta:
        ordering = ("-timestamp",)

    def __str__(self):
        return f"{self.name} - {self.elected_country}"

    def newly_added_ancestors(self):
        """
        The following ancestors were not recorded when the declaration was made; this
        can change the eligibility standing of the individual _if_ an ancestor was born
        in a country not already seen amongst the other ancestors.
        """
        pks = [s.pk for s in self.data]
        ancestors = [
            parent
            for parent in Parent.objects.filter(child=self.player).exclude(pk__in=pks)
        ]
        ancestors += [
            grandparent
            for grandparent in GrandParent.objects.filter(
                child__child=self.player
            ).exclude(pk__in=pks)
        ]
        return ancestors

    def now_eligible_for(self):
        """
        The ForeignKey to Player does not exercise the custom manager, so we need to perform another query.
        """
        return Player.objects.get(pk=self.player.pk).eligible()

    def clean(self):
        person_declaration_clean(self)


class DeclarationExceptionRequest(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    reason = models.TextField(
        help_text=(
            "Reason for the exception request. "
            "Provide explanation for why you are unable to meet the minimum requirements."
        )
    )

    def __str__(self):
        return f"{self.uuid} - {self.player}"


class Event(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    name = models.CharField(max_length=256)
    closing_date = models.DateField(
        blank=True, null=True, help_text="Closing date for nominations."
    )
    team_date = models.DateField(
        blank=True, null=True, help_text="Two weeks prior to closing date."
    )
    squad_date = models.DateField(
        blank=True, null=True, help_text="Three months prior to closing date."
    )

    class Meta:
        ordering = ("closing_date",)

    def __str__(self):
        return self.name


class NationalSquad(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    event = models.ForeignKey(Event, related_name="squads", on_delete=models.PROTECT)
    name = models.CharField(max_length=256)
    players = models.ManyToManyField(
        PlayerDeclaration,
        blank=True,
        limit_choices_to=models.Q(supersceded_by__isnull=True),
    )

    class Meta:
        unique_together = ("event", "name")
        ordering = ("event", "name")

    def __str__(self):
        return f"{self.name} - {self.event.name}"

eligibility/views.py
from typing import Any, Dict

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import Http404
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from guardian.decorators import permission_required
from guardian.shortcuts import assign_perm, get_objects_for_user

from eligibility.forms import (
    GrandParentForm,
    ParentForm,
    PlayerDeclarationForm,
    PlayerForm,
)
from eligibility.models import GrandParent, Parent, Player, PlayerDeclaration


def index(request):
    return TemplateResponse(request, "eligibility/index.html")


class PlayerList(LoginRequiredMixin, ListView):
    model = Player

    def get_queryset(self):
        return get_objects_for_user(self.request.user, "eligibility.change_player")


@login_required
def player_create(request):
    if request.method == "POST":
        form = PlayerForm(data=request.POST)
        if form.is_valid():
            instance = form.save()
            # XXX: This is really important! Without setting the change
            #      permission on the newly created object, it will not be
            #      editable in the player_edit view.
            assign_perm("eligibility.change_player", request.user, instance)
            return redirect(instance.get_absolute_url())
    else:
        form = PlayerForm()
    context = {"form": form, "cancel_url": reverse("players")}
    return TemplateResponse(request, "eligibility/player_form.html", context)


@permission_required("eligibility.change_player", (Player, "pk", "pk"))
def player_edit(request, pk):
    instance = get_object_or_404(Player, pk=pk)
    if request.method == "POST":
        form = PlayerForm(data=request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(reverse("players"))
    else:
        form = PlayerForm(instance=instance)
    context = {
        "object": instance,
        "form": form,
    }
    try:
        instance.can_declare()
    except ValueError as exc:
        context["declaration"] = str(exc)
    return TemplateResponse(request, "eligibility/player_form_detail.html", context)


@permission_required("eligibility.change_player", (Player, "pk", "player"))
def parent_edit(request, player, pk=None):
    child = get_object_or_404(Player, pk=player)
    if pk is None:
        instance = Parent(child=child)
    else:
        instance = get_object_or_404(child.parent_set, pk=pk)
    if request.method == "POST":
        form = ParentForm(data=request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(child.get_absolute_url())
    else:
        form = ParentForm(instance=instance)

    context = {
        "object": instance if pk is not None else None,
        "form": form,
        "player": child,
        "cancel_url": child.get_absolute_url(),
    }
    return TemplateResponse(request, "eligibility/parent_form.html", context)


@permission_required("eligibility.change_player", (Player, "pk", "player"))
def grandparent_edit(request, player, parent, pk=None):
    grandchild = get_object_or_404(Player, pk=player)
    child = get_object_or_404(grandchild.parent_set, pk=parent)
    if pk is None:
        instance = GrandParent(child=child)
    else:
        instance = get_object_or_404(child.grandparent_set, pk=pk)
    if request.method == "POST":
        form = GrandParentForm(data=request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(grandchild.get_absolute_url())
    else:
        form = GrandParentForm(instance=instance)

    context = {
        "object": instance if pk is not None else None,
        "form": form,
        "parent": child,
        "player": grandchild,
        "cancel_url": grandchild.get_absolute_url(),
    }
    return TemplateResponse(request, "eligibility/grandparent_form.html", context)


def declaration_create(request, player):
    player = get_object_or_404(Player, pk=player)
    try:
        player.can_declare()
    except ValueError as exc:
        raise Http404(f"Unable to make player declaration for {player}: {exc}") from exc
    instance = PlayerDeclaration(player=player)
    if request.method == "POST":
        form = PlayerDeclarationForm(data=request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(reverse("players"))
    else:
        form = PlayerDeclarationForm(instance=instance)
    context = {
        "object": instance,
        "form": form,
        "player": player,
        "cancel_url": player.get_absolute_url(),
    }
    return TemplateResponse(request, "eligibility/playerdeclaration_form.html", context)


class PlayerDeclarationView(LoginRequiredMixin, DetailView):
    model = PlayerDeclaration

eligibility/templates/eligibility/base_form.html
{% extends "base.html" %}
{% load bootstrap5 eligibility_tags %}

{% block container %}
    <main class="mt-3">
        <form class="card mb-3" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h4 class="card-header text-center">{% block card_title %}{% endblock %}</h4>
            <div class="card-body">
                {% block before_form %}{% endblock %}
                {% block form %}{% bootstrap_form form layout='horizontal' %}{% endblock %}
                {% block after_form %}{% endblock %}
            </div>
            {% block after_body %}{% endblock %}
            {% block card_footer %}
                <div class="card-footer">
                    {% bootstrap_button "Save" %}
                    {% bootstrap_button "Clear" button_type="reset" button_class="btn-secondary" %}
                    {% bootstrap_button "Cancel" button_type="link" href=cancel_url button_class="btn-link" %}
                </div>
            {% endblock %}
            {% block after_footer %}{% endblock %}
        </form>
    </main>
{% endblock %}

eligibility/templates/eligibility/base_formset.html
{% extends "base.html" %}
{% load bootstrap5 eligibility_tags %}

{% block container %}
    <main class="mt-3">
        <form class="card mb-3" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h4 class="card-header text-center">{% block card_title %}{% endblock %}</h4>
            <div class="card-body">
                {% block before_form %}{% endblock %}
                {% bootstrap_formset formset layout='horizontal' %}
                {% block after_form %}{% endblock %}
            </div>
            {% block after_body %}{% endblock %}
            {% block card_footer %}
                <div class="card-footer">
                    {% bootstrap_button "Save" %}
                    {% bootstrap_button "Clear" button_type="reset" button_class="btn-secondary" %}
                    {% bootstrap_button "Cancel" button_type="link" href=cancel_url button_class="btn-link" %}
                </div>
            {% endblock %}
            {% block after_footer %}{% endblock %}
        </form>
    </main>
{% endblock %}

eligibility/templates/eligibility/declarationexceptionrequest_form.html
{% extends "eligibility/base_form.html" %}
{% load bootstrap5 eligibility_tags %}

{% block card_title %}Exception Request{% endblock %}

{% block before_form %}
    <h5 class="card-title">{{ object|type|capfirst }} for {{ player }}</h5>

    <div class="alert alert-info" role="alert">
        <p>When a player is cannot complete their declaration because they are <strong>unable</strong>
            to provide all the requested details, they may <em>request</em> an exception from FIT to
            relax the constraints of this system, allowing them to proceed.</p>
        <p class="mb-0">FIT will review each request and if the reasons are accepted, can adjust the
            parameters of the declaration process.</p>
    </div>
{% endblock %}

{% block form %}
{% bootstrap_form form %}
{% endblock %}

eligibility/templates/eligibility/grandparent_form.html
{% extends "eligibility/parent_form.html" %}

{% block card_title %}{{ object.pk|yesno:"Update,Create" }} Grandparent{% endblock %}

{% block before_form %}
    <h5 class="card-title">{{ object.pk|yesno:"Update,New" }} grandparent for {{ parent.child }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">Parent for {{ parent }}</h6>
{% endblock %}

eligibility/templates/eligibility/index.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block page_title %}Player Eligibility Portal{% endblock %}

{% block container %}
    <main class="mt-3">
        <div class="row g-5">
            <div class="col-md-6">
                <div class="card">
                    <h5 class="card-header">Players</h5>
                    <div class="card-body">
                        If you're intending to play at a FIT tournament, you will need to provide us with details of your
                        birthplace and residency, as well as the birthplace of your parents and grandparents, in order to
                        determine which nations you're eligible for.
                    </div>
                    <div class="card-footer">
                        {% url 'players' as player_portal %}
                        {% bootstrap_button "Begin" button_type="link" href=player_portal %}
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <h5 class="card-header">Administrators</h5>
                    <div class="card-body">
                        After players have provided their details and nominated the nation they plan to represent, that
                        nation needs to verify them and also needs to declare any dual nationals who are selected in their
                        preliminary squads and final teams.
                    </div>
                    <div class="card-footer">
                        {% url 'nations' as nation_portal %}
                        {% bootstrap_button "Begin" button_type="link" href=nation_portal %}
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock container %}

eligibility/templates/eligibility/parent_form.html
{% extends "eligibility/base_form.html" %}

{% block card_title %}{{ object.pk|yesno:"Update,Create" }} Parent{% endblock %}

{% block before_form %}
    <h5 class="card-title">{{ object.pk|yesno:"Update,New" }} parent for {{ player }}</h5>
{% endblock %}

eligibility/templates/eligibility/player_form_detail.html
{% extends "eligibility/player_form.html" %}
{% load bootstrap5 %}

{% block card_footer %}{% endblock %}

{% block after_footer %}
    {% if object.pk %}
        <div class="card-body">
            <h5 class="card-subtitle mb-3">Ancestry</h5>
            {% if not object.can_declare_bool %}
                {% bootstrap_alert object.unable_to_declare_reason alert_type="warning" dismissible=True %}
            {% endif %}
            <div class="row row-cols-1 row-cols-md-2 g-4">
                {% for parent in object.parent_set.all %}
                    <div class="col">
                        <div class="card">
                            <div class="card-header d-flex justify-content-between align-items-center">
                                {% url 'parent' object.pk parent.pk as parent_url %}
                                <span>
                                    <a href="{{ parent_url }}">{{ parent }}</a>
                                    <span class="badge bg-info">{{ parent.birthplace }}</span>
                                </span>
                                <span class="badge rounded-pill bg-{{ parent.adopted|yesno:"info,primary" }}">{{ parent.adopted|yesno:"A,B" }}</span>
                            </div>
                            <ul class="list-group list-group-flush">
                                {% for grandparent in parent.grandparent_set.all %}
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                        {% url 'grandparent' object.pk parent.pk grandparent.pk as grandparent_url %}
                                        <span>
                                            <a href="{{ grandparent_url }}">{{ grandparent }}</a>
                                            <span class="badge bg-info">{{ grandparent.birthplace }}</span>
                                        </span>
                                        <span class="badge rounded-pill bg-{{ grandparent.adopted|yesno:"info,primary" }}">{{ grandparent.adopted|yesno:"A,B" }}</span>
                                    </li>
                                {% empty %}
                                    <li class="list-group-item">No grandparents entered, please add them.</li>
                                {% endfor %}
                            </ul>
                            <div class="card-footer">
                                {% url 'grandparent' object.pk parent.pk as create_grandparent_url %}
                                {% bootstrap_button "Add a grandparent" button_type="link" href=create_grandparent_url button_class="btn-secondary" size="small" %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="card-footer">
            {% bootstrap_button "Save" %}

            {% url 'parent' object.pk as create_parent_url %}
            {% bootstrap_button "Add a parent" button_type="link" href=create_parent_url button_class="btn-secondary" %}

            {% url 'declaration' player=object.pk as declaration_url %}
            {% url 'exception' pk=object.pk as exception_url %}
            {% with extra_classes=object.can_declare_bool|yesno:",disabled" %}
                {% bootstrap_button "Make declaration" button_type="link" href=declaration_url button_class="btn-secondary" extra_classes=extra_classes %}
                {% if not object.can_declare_bool and not object.declarationexceptionrequest_set.exists %}
                    {% bootstrap_button "Request exception" button_type="link" href=exception_url button_class="btn-secondary" %}
                {% endif %}
            {% endwith %}

            {% bootstrap_button "Clear" button_type="reset" button_class="btn-secondary" %}

            {% url 'players' as cancel_url %}
            {% bootstrap_button "Cancel" button_type="link" href=cancel_url button_class="btn-link" %}
        </div>
    {% endif %}
{% endblock %}

eligibility/templates/eligibility/playerdeclaration_detail.html
{% extends "base.html" %}
{% load bootstrap5 eligibility_tags %}

{% block container %}
    <main class="mt-3">
        <div class="card mb-3">
            <h4 class="card-header text-center">Player Declaration</h4>
            <div class="card-body">
                {% include "eligibility/playerdeclaration_detail_top.html" %}
                <h5 class="card-title">Ancestry</h5>
            </div>

            {% include "eligibility/playerdeclaration_detail_ancestry.html" %}

            <div class="card-footer">
                {% url 'players' as players_url %}
                {% bootstrap_button "Players" button_type="link" href=players_url %}
                {% bootstrap_button object.player button_type="link" href=object.player.get_absolute_url button_class="btn-secondary" %}
            </div>
        </div>
    </main>
{% endblock %}

eligibility/templates/eligibility/playerdeclaration_detail_ancestry.html
{% load bootstrap5 eligibility_tags %}

<table class="table table-striped mb-0">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Submission</th>
            <th scope="col">Changes</th>
        </tr>
    </thead>
    <tbody>
        {% for each in object.data %}
            <tr>
                <th>
                {{ each|type|title }}</td>
                <td>
                    {{ each.name }}
                    <span class="badge bg-primary">{{ each.country_of_birth|default_if_none:each.country_of_birth_other }}</span>
                    {% if each|type == "player" %}
                        <span class="badge bg-success">{{ each.residence|default_if_none:each.residence_other }}</span>
                    {% endif %}
                </td>
                <td class="p-0">
                    {% with dirty=each|dirty %}
                        {% if dirty %}
                            <table class="table mb-0 table-fixed">
                                {% for key, value in dirty.items %}
                                    <tr>
                                        <th class="col-4 col-xs-4">{{ each|fieldname:key|capfirst }}</td>
                                        <td class="col-4 col-xs-4 text-danger">{{ value.current|default_if_none:"-" }}</td>
                                        <td class="col-4 col-xs-4 text-success">{{ value.saved|default_if_none:"-" }}</td>
                                    </tr>
                                {% endfor %}
                            </table>
                        {% endif %}
                    {% endwith %}
                </td>
            </tr>
        {% endfor %}
        {% for each in object.newly_added_ancestors %}
            <tr>
                <th>{{ each|type|title }}</th>
                <td>-</td>
                <td class="p-0">
                    {% with dirty=each|model_to_dict:"child" %}
                        <table class="table mb-0 table-fixed">
                            {% for key, value in dirty.items %}
                                {% if value is not None %}
                                    <tr>
                                        <th class="col-4 col-xs-4">{{ each|fieldname:key|capfirst }}</th>
                                        <td class="col-4 col-xs-4 text-danger">-</td>
                                        <td class="col-4 col-xs-4 text-success">{{ value|default_if_none:"-" }}</td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </table>
                    {% endwith %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

eligibility/templates/eligibility/playerdeclaration_list_403.html
{% extends "simple.html" %}

{% block card_title %}Administrator Portal{% endblock %}
{% block card_body %}
    <p>Sorry {{ user.first_name }}, you don't have permission to access this section.</p>

    {% with "webmaster@tournaments.fit" as email %}
        <p class="mb-0">If you are a nation administrator, please email {{ email|urlize }} to request access.</p>
    {% endwith %}
{% endblock %}